### ISSUE TITLE
bf4.dll and bf4_x86.dll have the same info

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble-pahelper#2]
This probably happens because both plugins use the same plug name: **bf4plug**.
Mumble displays the correct info for both plugins.

![bf4_1](https://cloud.githubusercontent.com/assets/5897523/16910960/0245c406-4cdc-11e6-8594-c5dc93f84173.png)
![bf4_2](https://cloud.githubusercontent.com/assets/5897523/16910961/02488d08-4cdc-11e6-93db-42b425ed72b1.png)

**Comment by mkrautz** [comment]
It happens because they have the same shortname :)

**Comment by davidebeatrici** [comment]
And it detects the second plugin as a duplicate of the first... but why does Mumble see both plugins correctly? I guess it's a different plugin detection system, right?

**Comment by mkrautz** [comment]
@davidebeatrici In your list, BOTH of the plugins are x64.

What you're seeing is probably that one is a user plugin, and one is a system plugin.

**Comment by davidebeatrici** [comment]
No, I have no user plugins, the list only contains the system ones.

**Comment by mkrautz** [comment]
The shortname for x64 and x86 are probably the same.

The code that updates the display uses the short name to pick the plugin to show:
https://github.com/mumble-voip/mumble-pahelper/blob/master/mumblepahelper.cpp#L135

**Comment by mkrautz** [comment]
Should be simple enough to fix, let me try to submit a PR in a few...

**Comment by davidebeatrici** [comment]
Yes, the shortname is the same, I think that it's better to specify the architecture only in the long description :wink:

**Comment by mkrautz** [comment]
See https://github.com/mumble-voip/mumble-pahelper/pull/3 for a PR.
